### ISSUE TITLE
Eigenschap aantal van klasse Voorwaarden heeft geen type

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-moBurgers#1]
Link naar eigenschap: https://data.test-vlaanderen.be/doc/applicatieprofiel/mobiliteitsbudget/ontwerpstandaard/2023-01-16/#Voorwaarden%3Aaantal

Het verwachtte type is een `Int` of `Integer` (met hoofdletter)

**Comment by yarondassonneville** [comment]
Dit was inderdaad het geval in de oude versie van het specificatiedocument. Ondertussen is dit opgelost.
