### ISSUE TITLE
Eigenschap specificatie van klasse Voorwaarden heeft geen type

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-moBurgers#2]
Link naar eigenschap: https://data.test-vlaanderen.be/doc/applicatieprofiel/mobiliteitsbudget/ontwerpstandaard/2023-01-16/#Voorwaarden%3Aspecificatie

Het verwachte type is een `Document`, maar staat niet gedefinieerd op het diagram.

**Comment by yarondassonneville** [comment]
Dit was inderdaad het geval in de oude versie van het specificatiedocument. Ondertussen is dit opgelost.
