### ISSUE TITLE
Eigenschap mobiliteitsbudget van klasse Voorwaarden begint met een hoofdletter

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-moBurgers#3]
Link naar eigenschap: https://data.test-vlaanderen.be/doc/applicatieprofiel/mobiliteitsbudget/ontwerpstandaard/2023-01-16/#Voorwaarden%3Amobiliteitsbudget

De conventie is dat eigenschappen starten met een kleine letter ipv hoofdletter.

**Comment by yarondassonneville** [comment]
Dit was inderdaad het geval in de oude versie van het specificatiedocument. Ondertussen is dit opgelost.
