### ISSUE TITLE
UML-diagram op applicatieprofiel wijkt af van diagram in de .EAP file

### ISSUE THREAD

**Issue by ddvlanck** [Informatievlaanderen/OSLOthema-moBurgers#4]
Link naar UML: https://data.test-vlaanderen.be/doc/applicatieprofiel/mobiliteitsbudget/ontwerpstandaard/2023-01-16/html/overview.jpg

Op bovenstaand UML-diagram is duidelijk te zien dat er bv bij de klasse Voorwaarden enkele eigenschappen ontbreken (specificatie, aantal, mobiliteitsbudget), wat doet vermoeden dat dit UML-diagram een oudere versie is.

**Comment by yarondassonneville** [comment]
Dit was inderdaad het geval in de oude versie van het specificatiedocument. Ondertussen is dit opgelost.
